module.exports = {
  TARGET_ROLES: [
    'hiring manager',
    'talent acquisition',
    'manager recruitment',
    'ta manager',
    'manager - ta',
    'talent acquisition manager - tech',
    'manager of talent acquisition',
    'manager - human resources',
    'talent acquisition (tech)',
    'workforce staffing manager',
    'wfs',
    'recruitment manager',
    'head of talent',
    'head of recruiting',
    'recruiter',
    'sourcer',
    'talent acquisition specialist',
    'technical recruiter',
    'campus recruiter',
    'staffing manager',
  ],
};